language: objective-c
before_install:
    - brew update
    - brew unlink xctool
    - brew install xctool
xcode_workspace: TripMan.xcworkspace 
xcode_scheme: Location
before_script:
    - sudo easy_install cpp-coveralls
script: xctool -configuration Coverage clean test
after_success:
    - ./coveralls.rb --extension m --exclude-folder Demo --exclude-folder Test --exclude-folder Externals --exclude-folder Pods

