language: objective-c
before_install:
    - brew update
    - brew unlink xctool
    - brew install xctool
xcode_workspace: TripMan.xcworkspace 
xcode_scheme: Location
script: xctool -configuration Coverage -destination platform='iOS Simulator',OS=7.1,name='iPhone 5s' test
after_success:
    - ./coveralls.rb --extension m --exclude-folder Demo --exclude-folder Test --exclude-folder Externals --exclude-folder Pods

